services:

    recipe:
        synthetic: true

    input:
        class: Symfony\Component\Console\Input\ArgvInput
        
    output:
        class: Symfony\Component\Console\Output\ConsoleOutput

    style:
        class: Symfony\Component\Console\Style\SymfonyStyle
        arguments: ["@input", "@output"]

    application.command:
        class: Aes3xs\Yodler\Console\Command
        public: false

    application:
        class: Symfony\Component\Console\Application
        calls:
            - ["add", ["@application.command"]]
            - ["setDefaultCommand", ["@=service('application.command').getName()", true]]
            - ["setAutoExit", [false]]

    connection.phpseclib_client_factory:
        class: Aes3xs\Yodler\Connection\PhpSecLibClientFactory
        public: false

    connection.factory:
        class: Aes3xs\Yodler\Connection\ConnectionFactory
        public: false
        arguments:
            - "@connection.phpseclib_client_factory"

    connection.parameters:
        public: false
        class: Aes3xs\Yodler\Connection\ConnectionParameters

    connection:
        class: Aes3xs\Yodler\Connection\Connection
        arguments: ["@connection.factory", "@resource_resolver", "@logger"]
        calls:
            - ["setParameters", ["@connection.parameters"]]

    resource_locator.container_locator:
        class: Aes3xs\Yodler\ResourceLocator\ContainerResourceLocator
        public: false
        arguments: ["@service_container"]

    resource_locator.input_locator:
        class: Aes3xs\Yodler\ResourceLocator\InputResourceLocator
        public: false
        arguments: ["@input"]

    resource_locator.recipe_locator:
        class: Aes3xs\Yodler\ResourceLocator\RecipeResourceLocator
        public: false
        arguments: ["@recipe"]

    resource_locator.stacked_locator:
        class: Aes3xs\Yodler\ResourceLocator\StackedResourceLocator
        public: false
        calls:
            - ["addLocator", ["@resource_locator.recipe_locator"]]
            - ["addLocator", ["@resource_locator.input_locator"]]
            - ["addLocator", ["@resource_locator.container_locator"]]

    resource_locator: "@resource_locator.stacked_locator"

    resource_resolver:
        class: Aes3xs\Yodler\Resolver\ResourceResolver
        arguments: ["@resource_locator"]

    logger.console_handler:
        class: Aes3xs\Yodler\Logger\ConsoleHandler
        public: false
        arguments: ["@output"]

    logger:
        class: Monolog\Logger
        arguments: ["@=service('application.command').getName()"]
        calls:
            - [pushHandler, ["@logger.console_handler"]]

    runner:
        class: Aes3xs\Yodler\Runner\Runner
        arguments: ["@recipe", "@resource_resolver", "@reporter", "@logger"]

    reporter:
        class: Aes3xs\Yodler\Reporter\Reporter
        arguments: ["@style", "@logger"]

    shell:
        class: Aes3xs\Yodler\Service\Shell
        arguments: ["@connection"]

    composer:
        class: Aes3xs\Yodler\Service\Composer
        arguments: ["@shell"]

    git:
        class: Aes3xs\Yodler\Service\Git
        arguments: ["@shell"]

    releaser:
        class: Aes3xs\Yodler\Service\Releaser
        arguments: ["@shell"]

    symfony:
        class: Aes3xs\Yodler\Service\Symfony
        arguments: ["@shell"]
