parameters:
    command_builder.class: Aes3xs\Yodler\Console\CommandBuilder
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
    logger.class: Monolog\Logger
    console_handler.class: Symfony\Bridge\Monolog\Handler\ConsoleHandler
    console_formatter.class: Aes3xs\Yodler\Logger\ConsoleFormatter
    heap_factory.class: Aes3xs\Yodler\Heap\HeapFactory
    lazy_heap_proxy.class: Aes3xs\Yodler\Heap\LazyHeapProxy
    semaphore_factory.class: Aes3xs\Yodler\Deployer\SemaphoreFactory
    semaphore.class: Aes3xs\Yodler\Deployer\SemaphoreInterface
    report_factory.class: Aes3xs\Yodler\Deployer\ReportFactory
    report.class: Aes3xs\Yodler\Deployer\ReportInterface
    deploy_factory.class: Aes3xs\Yodler\Deploy\DeployFactory
    scenario_factory.class: Aes3xs\Yodler\Scenario\ScenarioFactory
    connection_factory.class: Aes3xs\Yodler\Connection\ConnectionFactory
    variable_factory.class: Aes3xs\Yodler\Variable\VariableFactory
    action_factory.class: Aes3xs\Yodler\Action\ActionFactory
    deploy_list.class: Aes3xs\Yodler\Deploy\DeployListInterface
    scenario_list.class: Aes3xs\Yodler\Scenario\ScenarioListInterface
    connection_list.class: Aes3xs\Yodler\Connection\ConnectionListInterface
    variable_list.class: Aes3xs\Yodler\Variable\VariableListInterface
    sftp_factory.class: Aes3xs\Yodler\Commander\SftpFactory
    commander_factory.class: Aes3xs\Yodler\Commander\CommanderFactory
    lazy_commander_proxy.class: Aes3xs\Yodler\Commander\LazyCommanderProxy
    deployer.class: Aes3xs\Yodler\Deployer\Deployer
    executor.class: Aes3xs\Yodler\Deployer\Executor
    deploy_context_factory.class: Aes3xs\Yodler\Deployer\DeployContextFactory

    verbosity_level_map:
        !php/const:\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_QUIET: error
        !php/const:\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_NORMAL: info
        !php/const:\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_VERBOSE: debug
        !php/const:\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_VERY_VERBOSE: debug
        !php/const:\Symfony\Component\Console\Output\OutputInterface::VERBOSITY_DEBUG: debug

    semaphore_lock_name: semaphore_lock_name
    report_lock_name: report_lock_name

services:

    event_dispatcher:
        class: '%event_dispatcher.class%'
        arguments: ['@service_container']

    command_builder:
        class: '%command_builder.class%'
        arguments:
            - '@deploys'
            - '@scenarios'
            - '@heap_factory'
            - '@deploy_context_factory'
        tags:
            - { name: kernel.event_subscriber }

    logger.console_handler:
        class: '%console_handler.class%'
        arguments:
            - null
            - true
            - '%verbosity_level_map%'
        calls:
            - [setFormatter, ['@logger.console_formatter']]
        tags:
            - { name: kernel.event_subscriber }

    logger.console_formatter:
        class: '%console_formatter.class%'
        public: false
        arguments: [null, null, true, true]
        calls:
            - [setHeap, ['@heap']]

    logger:
        class: '%logger.class%'
        arguments: [main]
        calls:
            - [pushHandler, ['@logger.console_handler']]

    heap_factory:
        class: '%heap_factory.class%'
        public: false
        arguments:
            - '@service_container'
            - '@variables'
            - '@variable_factory'

    lazy_heap_proxy:
        class: '%lazy_heap_proxy.class%'
        arguments:
            - '@heap_factory'
        tags:
            - { name: kernel.event_subscriber }

    heap: '@lazy_heap_proxy'

    semaphore_factory:
        class: '%semaphore_factory.class%'
        public: false

    report_factory:
        class: '%report_factory.class%'
        public: false

    semaphore:
        class: '%semaphore.class%'
        factory: 'semaphore_factory:create'
        arguments: ['%semaphore_lock_name%']

    report:
        class: '%report.class%'
        factory: 'report_factory:create'
        arguments: ['%report_lock_name%']

    sftp_factory:
        class: '%sftp_factory.class%'
        public: false

    commander_factory:
        class: '%commander_factory.class%'
        public: false
        arguments:
            - '@sftp_factory'

    lazy_commander_proxy:
        class: '%lazy_commander_proxy.class%'
        public: false
        arguments:
            - '@heap'
            - '@commander_factory'
            - '@logger'

    commander: '@lazy_commander_proxy'

    executor:
        class: '%executor.class%'
        public: false
        arguments:
            - '@heap'
            - '@report'
            - '@logger'

    deployer:
        class: '%deployer.class%'
        arguments:
            - '@deploy_context_factory'
            - '@executor'
            - '@event_dispatcher'
            - '@semaphore'
            - '@report'

    deploy_context_factory:
        class: '%deploy_context_factory.class%'
        public: false
        arguments:
            - '@deploy_factory'
            - '@scenario_factory'
            - '@connection_factory'

    deploy_factory:
        class: '%deploy_factory.class%'
        arguments:
            - '@scenarios'
            - '@connections'
            - '@variable_factory'
            - '@action_factory'

    scenario_factory:
        class: '%scenario_factory.class%'
        public: false
        arguments:
            - '@action_factory'
            - '@variable_factory'

    connection_factory:
        class: '%connection_factory.class%'
        public: false
        arguments:
            - '@variable_factory'

    variable_factory:
        class: '%variable_factory.class%'
        public: false

    action_factory:
        class: '%action_factory.class%'
        public: false
        arguments:
            - '@variables'
            - '@semaphore'
            - '@logger'

    deploys:
        class: '%deploy_list.class%'
        public: false
        factory: 'deploy_factory:createListFromConfiguration'
        arguments: ['%deploys%']

    scenarios:
        class: '%scenario_list.class%'
        public: false
        factory: 'scenario_factory:createListFromConfiguration'
        arguments: ['%scenarios%']

    connections:
        class: '%connection_list.class%'
        factory: 'connection_factory:createListFromConfiguration'
        arguments: ['%connections%']

    variables:
        class: '%variable_list.class%'
        public: false
        factory: 'variable_factory:createListFromConfiguration'
        arguments: ['%sources%']
