parameters:

    verbosity_level_map:
        0: 400      # VERBOSITY_QUIET:          ERROR
        1: 200      # VERBOSITY_NORMAL:         INFO
        2: 100      # VERBOSITY_VERBOSE:        DEBUG
        3: 100      # VERBOSITY_VERY_VERBOSE:   DEBUG
        4: 100      # VERBOSITY_DEBUG:          DEBUG

        16: 400     # VERBOSITY_QUIET:          ERROR
        32: 200     # VERBOSITY_NORMAL:         INFO
        64: 100     # VERBOSITY_VERBOSE:        DEBUG
        128: 100    # VERBOSITY_VERY_VERBOSE:   DEBUG
        256: 100    # VERBOSITY_DEBUG:          DEBUG

services:

    event_dispatcher:
        class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher
        arguments: ['@service_container']

    command_builder:
        class: Aes3xs\Yodler\Console\CommandBuilder
        arguments:
            - '@deploy_builder'
            - '%deploys%'
        tags:
            - { name: kernel.event_subscriber }

    deploy_builder:
        class: Aes3xs\Yodler\Deploy\DeployBuilder

    logger.console_handler:
        class: Symfony\Bridge\Monolog\Handler\ConsoleHandler
        arguments:
            - null
            - true
            - '%verbosity_level_map%'
        calls:
            - [setFormatter, ['@logger.console_formatter']]
        tags:
            - { name: kernel.event_subscriber }

    logger.console_formatter:
        class: Aes3xs\Yodler\Logger\ConsoleFormatter
        public: false
        arguments: [null, null, true, true]

    logger:
        class: Monolog\Logger
        arguments: [main]
        calls:
            - [pushHandler, ['@logger.console_handler']]

    heap_factory:
        class: Aes3xs\Yodler\Heap\HeapFactory
        arguments:
            - '@service_container'
            - '@commander_factory'
        tags:
            - { name: kernel.event_subscriber }

    semaphore_factory:
        class: Aes3xs\Yodler\Deployer\SemaphoreFactory

    reporter_factory:
        class: Aes3xs\Yodler\Deployer\ReporterFactory

    sftp_factory:
        class: Aes3xs\Yodler\Commander\SftpFactory
        public: false

    commander_factory:
        class: Aes3xs\Yodler\Commander\CommanderFactory
        public: false
        arguments:
            - '@sftp_factory'

    deployer:
        class: Aes3xs\Yodler\Deployer\Deployer
        arguments:
            - '@heap_factory'
            - '@logger'
