parameters:
    command_builder.class: Aes3xs\Yodler\Console\CommandBuilder
    event_dispatcher.class: Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher

services:

    event_dispatcher:
        class: '%event_dispatcher.class%'
        arguments: ['@service_container']

    command_builder:
        class: '%command_builder.class%'
        tags:
            - { name: kernel.event_subscriber}
